version: '3.9'

services:
  postgres:
    image: postgres:alpine
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pigeon-scoops-user
      - POSTGRES_DB=pigeon-scoops-db
      - POSTGRES_PASSWORD=password
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://pigeon-scoops-user:password@postgres:5432/pigeon-scoops-db